### ISSUE TITLE
Coordinates as double in netcdf

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/bufr2netcdf#10]
Citing a message from DWD:

> A minor remark ... the station coordinates (MLAH, MLOH) do not reflect the required accuracy of 25 bits.  Your file cdfin_synop.9 has these variables as "float", while our converter automatically chooses "double".

it appears that it is desirable to have station coordinates as double in netcdf (here we are speaking about synop, but I guess the mnemonic is common to other observations); I think this is not crucial, but if it is possible we could try to implement it.

**Comment by spanezz** [comment]
I've implemented this, hardcoded only for MLAH and MLOH.

Interestingly I had to add special exceptions in test cases, because the original netcdf data I had as a reference had float for those values:
https://github.com/ARPA-SIMC/bufr2netcdf/blob/master/src/convert-test.cc#L119

It might very well be that [the netcdf data I had as a reference](https://github.com/ARPA-SIMC/bufr2netcdf/tree/master/test/netcdf) is becoming obsolete

**Comment by spanezz** [comment]
I leave the issue open for review, let me know if this solves the issue

**Comment by spanezz** [comment]
I assume the issue is solved, and close the ticket
